public class Main {

    public static void main(String[] args) {
	// write your code here
        System.out.println("The Wolf 'Its a Fire-Graph' ");
        System.out.println("Day 1 ");
        System.out.print("I was walking through the forest this morning and I saw a wolf. ");
        System.out.println("It was just standing there.. Not doing anything. ");
        System.out.println("Then it turned it's head and looked at me.. ");
        System.out.println("It looked at me and I looked at it. We stared into each others souls... ");
        System.out.println("Then it turned around and ran away. Almost like it was trying to tell me something.. ");
        System.out.println("I stood there for the longest time.. Just thinking about what happened. ");
        System.out.println("I decided to head back home sense it was getting dark. ");
        System.out.println("But I thought I would head back to the forest tomorrow. ");
        System.out.println("Day 2 ");
        System.out.println("I went back to the forest and I brought some meat with me. ");
        System.out.println("I saw the wolf again. In the same exact spot as before. ");
        System.out.println("I put the meat down in front of me. Hoping it would come closer. ");
        System.out.println("It started to come closer. But it moved slowly and cautiously. ");
        System.out.println("I moved backwards a little. Hoping it wouldn't be as scared. ");
        System.out.println("It now stood in front of the meat and me. It ate the meat then it looked at me. ");
        System.out.println("It moved its head. Like it was thanking me. Then it took a few more steps. ");
        System.out.println("It now stood right in front of me.. I didn't know what to do. What was it doing? ");
        System.out.println("I put my hand out. I didn't know what I was doing. Nor did I know what was going to happen. ");
        System.out.println("It put its head to my hand and I froze. Then I moved my hand onto its head and petted it. ");
        System.out.println("It was like it wanted me to pet it.It stood there as I did. Then I pulled my hand away.. ");
        System.out.println("I remembered.. I had to get home! I looked at the wolf, smiled then left.. It was getting cold quickly. ");
        System.out.println("Then it was dark.. I could barely see. Then I tripped over something.. And I blacked out. ");
        System.out.println("Day 3" );
        System.out.println("When I woke up, I didn't know where I was but all I knew, was that the wolf was right next to me.. ");
        System.out.println("It had stayed with me all night. It had kept me warm. I sat up and the wolf did too. Like it cared about me. ");
        System.out.println("I looked at the wolf and I said thank you. It just looked at me just looking into my soul. Then it walked away.");
        System.out.println("I decided to whistle. It stopped and turned around. Then it came back. Like it knew what to do.. ");
        System.out.println("I asked it if it had a name. And it nodded its head. I asked it if it could tell me its name somehow. ");
        System.out.println("It walked over to a rose. I said 'Is your name Rose?' And it nodded its head. I looked the wolf up and down and I realized. It was a female wolf... ");
        System.out.println("I decided to head home. I was going to go home and get more meat for my new friend. ");
        System.out.println("I got home then grabbed some meat then started to head back to the forest. ");
        System.out.println("All of the sudden.. I heard gunshots off in the distance. It was coming from the forest! ");
        System.out.println("I started running as fast as possible. I wasn't going to let anyone hurt Rose. ");
        System.out.println("I saw rose growing at a hunter. I ran to the hunter and knocked him to the ground. ");
        System.out.println("I threw the gun out of the hunters hand. I told him to scram before I killed him. ");
        System.out.println("He ran like the chicken he was. I patted Rose on the head and asked 'Are you okay?' Rose nodded. ");
        System.out.println("I sighed with relief.. That was too close. I handed Rose the meat and she ate it. ");
        System.out.println("Rose sat down next me to. Almost like she was trying to tell me something. ");
        System.out.println("I pointed to a stick and said 'Write what you're trying to say..' Rose picked up the stick and started writing. ");
        System.out.println("I watched as she wrote. When she was done I looked at what she wrote. It said I am not a wolf.. I am trapped like this. ");
        System.out.println("I looked at Rose at said 'What..?' Rose looked at me and nodded. I asked her what her real name was. She grabbed the stick. ");
        System.out.println("She wrote My name is Abby. I looked at her and said 'Wait.. Abby? Abby L..?' And Rose looked at me and nodded slowly. ");
        System.out.println("I touched her head gently and said 'Abby. Do you recognise me..?' And she nodded and wrote my name in the sand.. ");
        System.out.println("Evan.. And I realized that she had been missing for 4 days.. Now i knew where she had been.. ");
        System.out.println("I didn't want to go home. But I had to.. So I left the forest and went home. ");
        System.out.println("Day 4 ");
        System.out.println("I came back to the forest and she was there waiting for me. ");
        System.out.println("I told her to follow me and she did. We walked in the woods then there was a wood cabin. I thought hmm that was not there before. ");
        System.out.println("I knocked on the door and a guy opened the door and he said 'Can I help you?' I said 'I am Evan this is Abby my wolf.' ");
        System.out.println("Oh he said 'I am Alex. What are you doing so deep in the woods?' I said 'We were just walking. Can we stay here?' ");
        System.out.println("He says 'Oh of course! It is quite a long ways to any other place.' I walked into his house but Abby sat down outside. ");
        System.out.println("'You okay?' I asked her. She nodded but remained seated on the ground. ");
        System.out.println("I decided to walk around his house a little then walked back outside. Abby was waiting for me. ");
        System.out.println("Alex walked out after me and said 'So how long have you had a pet wolf for?' I said 'Not too long..' ");
        System.out.println("He smiled and said 'Hm that is pretty cool!' I said 'Yeah kind of.. Except she is not actually a wolf. She is stuck like that.' ");
        System.out.println("He said 'What? You are telling me that is actually a human??' And I said 'Yeah..' ");
        System.out.println("He sighed and said 'How long has she been stuck like this..?' I said 'Eight days now..'");
        System.out.println("He said 'I am so sorry..' I said 'It is fine. We just need to get her back to normal..' ");
        System.out.println("He said 'Let us get some rest first.. We can get help tomorrow..' I said 'Alright..' And we headed inside. ");
        System.out.println("Day 5 ");
        System.out.println("When we woke up.. I noticed Abby was not there. I looked around the entire house then panicked. ");
        System.out.println("I said to Alex 'Alex! Abby is gone.. Where could she be..?' He said 'I do not know..' 'We have to find her!' ");
        System.out.println("'Lets scan the woods..' 'Yeah that is a good idea.' I said. We started looking around the woods. Then I spotted something.");
        System.out.println("There was something lying on the ground and I immediately ran up to it. It was Abby.. She seemed to be hurt but still alive. ");
        System.out.println("I picked her up carefully and we ran back to the house. Alex grabbed some bandages and we carefully wrapped her wound. ");
        System.out.println("'That was too close.. She could have died..' 'I know Alex.. We have to be careful.' ");
        System.out.println("'Yeah we do! The second we leave her alone She disappears and gets hurt! We can not let her out of our sights..' ");
        System.out.println("'I realize that Alex. We just have to be careful. One of us should get medicine.' ");
        System.out.println("'That is actually a good idea.. I will head into town and see if anyone can help us.' ");
        System.out.println("I watched as Alex walked down the path towards town. I waited about three hours and he finally came back. ");
        System.out.println("'I got some medicine and I made a new friend!' Someone came out from behind him. She said 'Hey! I am Lex.' ");
        System.out.println("'Nice to meet you Lex. Did Alex explain our problem?' 'Yeah he did.. Luckily I have this bag.' ");
        System.out.println("She pulled off her backpack and set it down then pulled out some medicine and some kind of drink. ");
        System.out.println("'Have her take this drink and medicine when she wakes up. It will heal her and hopefully turn her normal.' ");
        System.out.println("'Okay I will make sure she does. Thank you Lex.' 'No problem.' 'I just hope it works.' 'I hope it works too..' ");
        System.out.println("'She has been stuck like this for quite some time now.. It would be nice to help her out.' ");
        System.out.println("I noticed something was wrong with Abby. She was not in the same position as before.. ");
        System.out.println("I gently touched her head as I wondered what was wrong then she moved and sat up. ");
        System.out.println("I looked at her and said 'Hey! You alright?' She nodded slowly and looked at one of the windows. ");
        System.out.println("'What are you looking at?' I asked her. She lifted her paw and pointed at the setting sun. ");
        System.out.println("'Oh it is getting dark. You are right. Lets get some rest.' And we all went to bed. ");
        System.out.println("Day 6 ");
        System.out.println("I woke up and Abby was sleeping right next to me. Kind of cute. ");
        System.out.println("I petted her slowly and gently trying not to wake her. ");
        System.out.println("I decided I would get up and make some breakfast. It was early but I was hungry. ");
        System.out.println("I went to the kitchen and started making some pancakes. I heard some footsteps and saw Alex. ");
        System.out.println("'Oh hey Alex!' 'Hey Evan. Why are you up so early?' 'I could ask you the same thing.' I laughed quietly. ");
        System.out.println("'I am not sure but I am hungry so I am making some pancakes. Want any?' 'Sure why not.' He said. ");
        System.out.println("When I finished the pancakes we ate them and I washed the dishes. ");
        System.out.println("I decided to head back to the bedroom to check on Abby. She was walking around almost pacing. ");
        System.out.println("'Hey you okay?' She stopped in her tracks and looked at me then sat down. ");
        System.out.println("I walked over to her and sat down in front of her. She looked at me. I noticed her eyes were a different color. ");
        System.out.println("'Are you okay..?' She looked at me and moved her paw and poked me. 'What?' I asked her. ");
        System.out.println("She looked down at the ground and slowly I realized she was turning back to normal. ");
        System.out.println("She turned back to normal after all this time. I looked at her and said 'Abby..?' ");
        System.out.println("She looked up at me and smiled. 'Evan. It is good to see you again.' I laughed quietly. 'Yeah it is.' I said. ");
        System.out.println("She got up off the ground and started walking around. 'Hey Alex!' Alex turned around and looked at her. ");
        System.out.println("'Abby! Welcome back.' 'Thank you. Oh hey Lex!' Lex also turned around. 'Abby. Welcome back to normal.' ");
        System.out.println("'Thank you so much. All of you. I was stuck like that for.. Ten days..' She paused then said 'Wow..' ");
        System.out.println("'Ten whole days..' I saw a glimpse of sadness in her eyes. 'I am so glad you found me..' ");
        System.out.println("'I am glad I found you too. You could have been stuck like that for a long time.' ");
        System.out.println("I saw her look out of the window again. 'Wow. It is almost night time again.. That went by fast.' ");
        System.out.println("'Lets get some rest. We have a long day tomorrow.' ");
        System.out.println("Day 7 ");
        System.out.println("I could not sleep for some reason. I tried to and could not.. Evan was asleep. So were Lex and Alex. ");
        System.out.println("But me? Nope. I just could not sleep. I decided to go through the attic. Just to see if there was anything cool.");
        System.out.println("I saw a chest of some kind. I opened it and started looking through it. ");
        System.out.println("I had found something interesting.. Something I had seen before but it was a memory.. ");
        System.out.println("It was a picture of us all.. Of me Alex Evan and Lex... But it was a different memory.. like a different world?");
        System.out.println("I put the picture into my pocket. I kept thinking about it.. I wondered. Why would this be up here... ");
        System.out.println("Then I remembered.. Part of our memories had been taken from us.. And I remembered.. Everything.....");
        System.out.println("Ten days later...");
        System.out.println("Day 17 ");
        System.out.println("I woke up and she was asleep in her bed. I rubbed my eyes and thought Maybe it was a dream.. ");
        System.out.println("I wanted to get up but my energy felt drained.. Like empty.. So I just decided to lay there. ");
        System.out.println("I saw her get up and she yawned then she walked over to me and said 'Tired?' 'Yeah..' ");
        System.out.println("'You look tired.' She said. 'Yeah. I feel like I have been drained or something.' She laughed. ");
        System.out.println("'That is weird.' She said then smiled but almost creepily. 'What?' I asked her. 'Oh nothing' she smiled. ");
        System.out.println("'Okay then' I said. I looked at her. Her hair looked really pretty. Her eyes almost sparkled. ");
        System.out.println("'Your hair looks amazing.' I said. 'Thank you.' I realized she was wearing a dress. She was not wearing one before.");
        System.out.println("I all of the sudden had the urge to sit up. I felt like I needed to leave now. ");
        System.out.println("I got up and walked out of the room quickly. Something was definitely wrong. Then Abby was following me. ");
        System.out.println("She had a knife in her hand and I ran into the forest then she threw the knife it hit me in the back.. ");
        System.out.println("Then I woke up and sat straight up.. ");
        System.out.println("Day 8");
        System.out.println("What a terrible dream. I felt like I was gonna throw up from that. ");
        System.out.println("So I decided to get up and went to the kitchen to get a glass of water. I got the glass and drank my water. ");
        System.out.println("I kept thinking about the dream. Trying to figure out if it meant something. ");
        System.out.println("I went back to the bedroom. Everyone else was still asleep. I decided to go outside and look around. ");
        System.out.println("There was not much to see. I went back inside and Abby was sitting on the ground ");
        System.out.println("'Hey' I sat down next to her. 'Hey' She looked at me. 'You tired?' I asked her. 'Yeah a little.' She said. ");
        System.out.println("She stood up and so did I. I was going to leave the room then something told me to stay. ");
        System.out.println("I turned around and Abby was standing at the window. I saw a flash of something. I blinked several times. ");
        System.out.println("I thought I was losing my mind. She turned around and looked at me. 'Evan? Are you ok?' 'Yeah sorry.' ");
        System.out.println("I felt dazed. I thought I had seen something next to her. But there was nothing there. ");
        System.out.println("I had to make sure I was not still dreaming. I pinched myself. I was not sleeping. ");
        System.out.println("I must have been seeing things. I decided to just sit on the edge of the bed for a few minutes. ");
        System.out.println("I got up after a little while. I ate a sandwich and thought about what had happened. ");
        System.out.println("I realized it was getting dark out and we all went to bed. ");
        System.out.println("Day 9 ");
        System.out.println("I realized Abby still had not woken up. I tried to wake her but she was completely knocked out. ");
        System.out.println("I was concerned but I let her sleep. ");
        System.out.println("Day 10");
        System.out.println("I woke up and everyone else was already up and they were all looking at me concerned. I sat up. ");
        System.out.println("'What? Why are you all looking at me like that..?' 'Abby.. You were out for three days..' ");
        System.out.println("Day 12 ");
        System.out.println("'What do you mean by I was out for three days..' 'You got knocked out you have been out for three days.' ");
        System.out.println("'So you are telling me it has been three days.. And I did not know because of that.?' 'Yeah..' ");
        System.out.println("'Oh my god..' I said quietly.. It had been three days.. And I had gotten knocked out?? How? Why? ");
        System.out.println("I could not believe it.. I decided to get up and walk around. I pulled the picture out of my pocket. ");
        System.out.println("I looked at the picture for a while. Then I noticed something in the background of the picture. ");
        System.out.println("There was a wolf in the background of the picture. That was not there before.. Or was it? Was it my calling card?");
        System.out.println("Did I need to go into the woods? Did I need to search for something? What was it supposed to mean? ");
        System.out.println("Six days later... ");
        System.out.println("Day 18 ");
        System.out.println("'Abby are you okay?' She looked tired and exhausted. 'I am okay. Just feel weird.' ");
        System.out.println("'Do you want some water?' 'No thank you' I wonder why he asked me if I wanted water. That would not help me. ");
        System.out.println("Then again. He did not know about the other side of me. He knew I was part wolf but not about the other side. ");
        System.out.println("I did not want to tell him. I did not want him to be scared of me. So I kept it a secret for a long time. ");
        System.out.println("I realized I was getting more tired quickly. I needed blood. That is the other part. I am part vampire. ");
        System.out.println("I decided to head into the woods and luckily I found a bird. It would do for blood. I came back to the house. ");
        System.out.println("I was still slightly dizzy but it would have to do. It is hard to find blood that I can drink. ");
        System.out.println("I am surprised that my friends have not noticed it yet. But I am pretty good at keeping secrets. ");
        System.out.println("I really needed more but I could not find any more. I would have to deal with the dizziness. ");
        System.out.println("I am not supposed to drink human blood. That is why my friends do not know about it. ");
        System.out.println("I do not want to hurt them accidentally. That is why I avoid human blood. ");
        System.out.println("I always have to pretend like I went for a walk. Which I do not mind. It is just annoying. ");
        System.out.println("Six days later...");
        System.out.println("Day 24 ");
        System.out.println("I kept almost throwing up. I had not been getting enough blood to survive like this. ");
        System.out.println("I did not want to tell Evan about this. But I knew now that I had to. ");
        System.out.println("I needed blood now or else I could die. I had to tell him. ");
        System.out.println("'Hey Evan. There is something I think you should know..' He seemed to be slightly surprised. ");
        System.out.println("Although he did not seem mad or upset. I remember him telling me I could bite his arm. ");
        System.out.println("I told him I did not want to accidentally hurt him. The last thing I remember.. Was feeling dizzy. ");
        System.out.println("And faintly hearing him say my name as all I saw was darkness. Then nothing afterwards.. ");
        System.out.println("Day 25 ");
        System.out.println("I woke up the next day. Still dizzy and feeling weird. Evan was sitting there with me. ");
        System.out.println("'Hey' I realized I sounded weird. He told me I needed to have some of his blood. ");
        System.out.println("I knew I did not want to. But I had to. So I bit his arm gently. ");
        System.out.println("Afterwards I started to feel better and slowly could actually see my surroundings. ");
        System.out.println("'You feeling better?' 'Yeah a bit.' I hated needing blood but it was part of me now. ");
        System.out.println("I wanted to gt rid of the need for blood. But I did not know how to. ");
        System.out.println("I decided to look it up. But what I found would be too risky. I would have to get hit with an arrow. ");
        System.out.println("It did not make sense. There had to be some other way. But that was the only option that came up. ");
        System.out.println("It was not worth the risk.. But in the end. I did not want to be like this. So I headed into the woods. ");
        System.out.println("I knew there would be hunters. Like there was one before. So I turned into my wolf form and waited. ");
        System.out.println("It was not long before I saw a hunter. I pretended not to see him until he broke a stick. ");
        System.out.println("I looked up towards the hunter. I decided to stand up and growl softly. ");
        System.out.println("I saw him hold up the loaded crossbow. I closed my eyes. Knowing what was about to happen. ");
        System.out.println("I felt the arrow pierce my skin. I remember flinching a little then I started to run away. ");
        System.out.println("I remember seeing the house off in the distance. I decided to howl. Evan somehow heard the howl. ");
        System.out.println("I saw him come running into the woods. I remember feeling weak and falling to the ground onto my side. ");
        System.out.println("He pulled the arrow out of my side and I turned back to my human form. 'I am sorry for going outside alone.' ");
        System.out.println("He helped me up and helped me get back to the house. 'Thank you.' I realized this could have been a serious mistake. ");
        System.out.println("After I bandaged the wounded area I walked around the house a little. I was still in pain. ");
        System.out.println("I did not mind though. I just hoped that it had worked. I realized the hunter might have followed me. ");
        System.out.println("I went back into the woods and found the hunter sitting in a clearing. It looked like they were crying. ");
        System.out.println("I turned back into my wolf form then walked up to them and nudged their hand. ");
        System.out.println("They looked at me and realized I was the same wolf as before. I could tell he was upset about hurting me. ");
        System.out.println("But why? I sat down in front of them and nudged their hand again. They clearly did not know what to do. ");
        System.out.println("I decided to lay down next to them. They started to pet me. They finally figured out what to do. ");
        System.out.println("I got up and sat back down in front of them then I turned to my human form. ");
        System.out.println("'Hello.' They looked at me for a few seconds. 'Hi.. I am sorry for hurting you.' ");
        System.out.println("So they were upset about that... 'No it is okay. You did not know.' They looked at me and smiled. ");
        System.out.println("'My name is Phoenix' She said. 'That is such a pretty name' Wow.. She had a really awesome name. ");
        System.out.println("I noticed something familiar about her. She looked familiar.. But I had never met her before? ");
        System.out.println("I asked her if she went by another name. 'Yeah actually. Most people usually call me Abby. I am looking for the other version of me.' ");
        System.out.println("I froze immediately then stood up immediately and so did she. 'Abby.. I am that other Abby..' ");
        System.out.println("She looked at me then said 'I am here to warn you.. Do not trust Alex. He plans to kill you.' Then she disappeared. ");
        System.out.println("I stood there for a long time. Then I ran back to the house. 'Evan!' 'Abby? What is wrong?' ");
        System.out.println("I explained to him what had just happened. He looked at me. 'Wow..That is weird..' ");
        System.out.println("I thought about it for a while. Maybe that is why I found that picture... ");
        System.out.println("Although I needed to get sleep. I was tired and it was really late. ");
        System.out.println("But then again. Was sleep really necessary? Nah. I decided I would stay up all night. ");
        System.out.println("Would I regret this? Probably. Oh well. What could possibly go wrong..? ");
        System.out.println("Day 26 ");
        System.out.println("It was finally the next day. I was super tired now from not sleeping. ");
        System.out.println("It felt like it was still night time. I decided to get up and walk around. ");
        System.out.println("'Hey Evan..' 'Hey! You sound tired. You alright?' 'Yeah I am okay.' ");
        System.out.println("I kept wondering if he could tell that I was lying. I just had to act awake. ");
        System.out.println("I was so tired. I wanted to sleep but I also did not want to. ");
        System.out.println("I decided to lay down. 'You alright?' 'Yeah I am just tired..' ");
        System.out.println("I could feel myself falling asleep. I did not want to sleep but I was so tired.. ");
        System.out.println("Then I passed out. ");
        System.out.println("Day 8...? ");
        System.out.println("I woke up in my own house. How did I get here..? I realized I was human. I tried to turn into a wolf. ");
        System.out.println("It did not work... Why could I not transform..? This must have been some kind of mistake.. ");
        System.out.println("I looked at what time it was. It was 3:44 AM..? What the heck.. ");
        System.out.println("I tried to find my mask so that maybe I could transform.. I could not find it.. ");
        System.out.println("It was not here at all.. This must be a nightmare.. I started to get paranoid. ");
        System.out.println("I pulled out my phone to text Evan.. And his contact was gone.. Like it never existed... ");
        System.out.println("I tried to text Lex and Alex but their contacts were gone as well.. Why was this happening..? ");
        System.out.println("I decided I would go for a walk.. To see if I could find either of them... ");
        System.out.println("I heard Alex scream.. I ran as fast as I could in that direction. ");
        System.out.println("I saw him being stabbed with a knife then he fell to the ground. Whoever had done it had left quickly. ");
        System.out.println("I ran over to Alex, But it was already too late.. I got up and left. Hoping I could find my other friends.. ");
        System.out.println("Before it was also too late... I decided to run to the forest to look. ");
        System.out.println("I heard Lex scream and I ran even deeper into the woods. When I found her she was already dead.. ");
        System.out.println("Her eyes had been picked out by birds.. Kind of gross.. I decided to keep going deeper into the forest to find Evan..");
        System.out.println("I needed to find him.. I did not want to lose him. I heard a footsteps behind me and a gun get loaded. ");
        System.out.println("I froze. I knew the gun was aimed at me.. I did not know what to do.. ");
        System.out.println("I heard Evan call out my name.. I closed my eyes.. Knowing I was about to die... ");
        System.out.println("But then, all of a sudden, lightning flashed around me, and I was somewhere else");
        System.out.println("I looked up and saw Evan, I was lying on the ground and he was sitting next to me, holding my hand");
        System.out.println("He had somehow unlocked the power of the speed equation and ran faster than the speed of sound,");
        System.out.println("The bullet was in his hand, and he let it drop to the ground. ");
        System.out.println("I could not believe what had just happened.. He had saved me.. In only a few seconds.. ");
        System.out.println("'I.. uh.. T-thank you..' 'Of course.. I was not going to let you die.' ");
        System.out.println("I looked back at him. How could he have run that fast.. It is almost impossible to run that fast.. ");
        System.out.println("I sat up and held his hand. The sunlight reflected onto his eyes.. So pretty... ");
        System.out.println("His squid hat glistening the sun. ");
        System.out.println("But then, the man behind the slaughter, walked up, his gun pointed at me. ");
        System.out.println("'It was I, Alexander Lambelton, the man you left behind that night to die in pain!' ");
        System.out.println("All of the sudden I saw Lex appear behind Alex. She was a ghost and then she snapped his neck. ");
        System.out.println("Then they both disappeared and I looked back at Evan. 'What the heck just happened..'  ");
        System.out.println("'I am not sure Abby.. I am just glad you're okay..' He pulled me to him and hugged me. ");
        System.out.println("Yeah, Sure I was okay.. But for some reason.. I did not feel safe.. ");
        System.out.println("In front of us, the Ancient One, appeared from a portal.");
        System.out.println("'Hello Abby and Evan, as much as this moment is heartwarming, it must come to an end.'");
        System.out.println("'Your death, Abby, is an absolute point in time'");
        System.out.println("'Absolute?' Evan questioned");
        System.out.println("'Unchangeable, unmovable.  Without her death, you will never have defeated Demascus, and become the speedster supreme.'");
        System.out.println("'Im creating a paradox' Evan said as he stood, offering his hand to help me up");
        System.out.println("'Im sorry, but this timeline has to be destroyed. it is impossible for her to live in a universe where you live as well'");
        System.out.println("'Nothing is impossible, you taught me that! I only require more power.");
        System.out.println("I looked back and forth at both of them. I was so confused about what was happening.. I did not want to die. But I did not know what was happening either.. ");
        System.out.println("'Im sorry, Evan, but I must do this' , the Ancient One conjured a chain and threw it towards me. I screamed in terror and agony as i felt the world fall apart around me..");
        System.out.println("I woke up...");
        System.out.println("Day 27 ");
        System.out.println("I sat up. Completely terrified about what I had just witnessed.. I really hoped it was just a dream.. ");
        System.out.println("I wanted to get up and make sure my friends were okay.. But I also did not want to get up because I was too scared to move. I could hear myself panting.. ");
        System.out.println("I layed back down and curled up. I did not want it to have been real.. I wanted to cry.. I did not know if my friends were in the house or not.  ");
        System.out.println("What if they had been killed.. What If I was dead and I did not realize it.. I decided to get up anyways. I walked downstairs and I saw Evan in the kitchen. ");
        System.out.println("I was so happy. I ran up to him and hugged him tightly. 'Abby. Whoa, what is wrong?' 'Nothing. I am just really glad to see you..'  ");
        System.out.println("I was so glad that it was just a dream.. I did not want to be dead.. Or my friends to be dead either.. ");
        System.out.println("Evan pushed my hair back and gave me a kiss on the cheek. I could feel myself blush a little. I still felt paranoid about the dream. ");
        System.out.println("I pulled him to me and hugged him again. This is what I wanted.. A nice person to be with and someone who cared about me. ");
        System.out.println("I walked away and looked out the window. It was snowing? It was kind of early for it to be snowing.. ");
        System.out.println("I decided I would go for a walk outside. 'Where are you going?' 'Just outside. Don't worry, I will be careful.' And I went out into the snowy woods.. ");
        System.out.println(" But then, as i am walking, I see a snowman in front of me and it starts bombarding me with snowballs. ");
        System.out.println("I started to get covered with snow.. There was no way out. I was stuck. 'EVAN!!' I shouted his name as loud as I could as I was slowly being covered with the freezing snow.. ");
        System.out.println("I started to realize there might not be an escape.. I was almost completely covered with snow.. I was freezing and I knew I was.. I could tell I was having trouble staying awake..");
        System.out.println("Out of nowhere, a pack of wolves attacks the snowman and rips it apart. When they got done, they came to me and dug me out. Then, they left. ");
        System.out.println("I was still freezing a little. I ran back to the house. 'Abby! Are you okay?' I looked at him then I passed out. ");
        System.out.println("Day 28 ");
        System.out.println("I woke up a little bit.. I was on the bed wrapped in a blanket. I curled up and looked around a little. 'Good morning. You feeling alright?' ");
        System.out.println("'Yeah.. kind of dizzy though..' He rubbed my back and head gently.. 'It is going to be okay..' 'I know..' I moved closer to him and rested my head on his chest. ");
        System.out.println("I wanted to thank the wolves that saved me.. But I had no clue where they had gone afterwards. I kept wondering how they knew where I was... ");
        System.out.println("Or why they saved me at all... But I did not want to go back out into the snow.. That was too dangerous. I decided I would grab a jacket then head back outside. ");
        System.out.println("'I will be back..' I got up and headed outside. I started looking for the wolves and came across a frozen lake. I decided to cross it as a shortcut. ");
        System.out.println("This would be the greatest mistake in my entire life.. The ice broke from underneath my feet and I fell into the freezing water. ");
        System.out.println("I knew I was not a good swimmer, so I started to panic.. Was this how I was going to die..? 'Evan! S-someone! Help!' I kept taking in water trying to call for help.. ");
        System.out.println("I was running out of energy.. I could not stay above the water for much longer.. I was struggling to stay calm now too.. I was freezing slowly now.. ");
        System.out.println("I screamed Evans name once more.. Then I could tell I was starting to lose consciousness.. This was it.. This was how I was going to die... ");
        System.out.println("As my vision went dark.. I saw a blurry figure and heard someone say my name.. Then everything went black.. ");
        System.out.println("When I was starting to wake up.. I was struggling.. I felt warm and cold.. I slowly regained consciousness.. ");
        System.out.println("I looked up at a blurry figure... They were holding me close.. Almost cradling me.. I could tell they were crying.. ");
        System.out.println("When my vision returned.. I saw it was Evan.. He was definitely crying.. But why.. 'Evan..?' He looked down at me.. 'Abby..!' He held me closer and hugged me. ");
        System.out.println("'Evan, What is wrong..?' I sat up and he looked at me. 'I thought..' He paused and sighed. 'You almost died..' I looked at him. 'I know...' ");
        System.out.println("'You-?' 'Yes Evan.. I know I almost did.. You are the one who saved me.. Weren't you..?' He nodded. I hugged him again. 'Thank you.' I whispered into his ear. ");
        System.out.println("I kissed him, then got up and left. I have never walked so fast before. I grabbed a glass of water and chugged it. I felt so nervous.. ");
        System.out.println("'I am not going out there again..' I mumbled to myself. I was not ready to die. I was not going out there by myself ever again. ");
        System.out.println("I went back into the bedroom and hugged Evan from behind. 'I love you.' 'I love you too Abby.' I wanted to stay like this forever. But it didn't last long.. ");
        System.out.println("All of the sudden, a strange man broke into the house and he had a sword in his hand. Evan for some reason had a sword in his holster. ");
        System.out.println("Evan pulled out the sword as well and they began fighting each other. I stepped back, unsure about what to do. ");
        System.out.println("The guy cut Evans arm, then Evan cut his eye. I was terrified. How could I help him..? The guy went to stab Evan and..... ");
        System.out.println("Before I even realized it. I was starting to panic. Should I use my powers..? ");
        System.out.println("Then the guy stabbed Evan... 'tis but a flesh wound.' I realized now that this was worse than planned. ");
        System.out.println("I didn't even realize what had happened. But I had ran so fast, Transforming into a wolf and tearing the guy to shreds. ");
        System.out.println("I turned back into a human and ran to Evan who had fallen onto the ground. 'Evan!!' I lifted him up slightly onto my lap.. Looking at all the blood... ");
        System.out.println("'E-evan please.. Hold on...' My voice was breaking.. I started crying.. I wasn't ready to lose him.. 'Please D-don't die on me...' ");
        System.out.println("'Abby... I love you..' I was sobbing now.. 'I love you too...' He was losing his strength and I knew he was.. I kissed him on the forehead.. ");
        System.out.println("I kept hoping that somehow.. He would be okay,, But I didn't know how to heal him without hurting myself... 'Please hold on...' ");
        System.out.println("I didn't want to lose him.. 'Thank you for trying.. Abby...' I looked down at him and he was gone.. He w-was gone... I sobbed even more... ");
        System.out.println("No no no no no..... This wasn't happening.... He c-couldn't be gone.... This had to be a nightmare.... Why... WHY!?... ");
        System.out.println("I got up from the floor and went to the bedroom. I was still crying... I sat down on the bed.. Not sure about what to do... ");
        System.out.println("All of the sudden Evans sweatshirt appeared right next to me.. I looked at it confused and then put it on.. God.. I didn't want to live without him.... ");
        System.out.println("What was I supposed to do.... I felt empty... He was gone... Then I saw him.. His ghost sat down next to me on the bed.. ");
        System.out.println("'Abby'.... I sat up and started to tear up.... 'Abby, I have unfinished business. I can only go to heaven if i help you.");
        System.out.println("'Help me with what?' i said with a sob in my voice....'i ned you to do something for me'...'tell me'...");
        System.out.println("Evan grabbed me with on my shoulders and put his mouth to my ear...'Wake up'");










    }
}
